# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 937c762cc9d06092e4a01c0b6db846ccbd76128e1a87e2d5df0bb92682d3e66dbee69e1d76129642510a96c872639ba15ea83007755af77b68b08cedcca23c5a

test:
  secret_key_base: 9eb1c32780a98f7f403eabb62c22d7ec748317ccfe2f08a05c72f71f9afca442ff827f51137450f76891f6d21b859499a707c46611fe1bfb499a0457870efa8e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
